# -*- coding: utf-8 -*-
"""DataCleaning2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZqgK7vPDuPI192d3CVFavqhmCKVFb_ei
"""

from google.colab import drive
drive.mount('/content/drive')

import os

!pip install striprtf
from striprtf.striprtf import rtf_to_text

import pandas as pd
from pandas.io.common import file_exists
from collections import defaultdict

file_path='/content/drive/MyDrive/Tesi_Polifonia/file_88_90'
path = os.chdir(file_path)
rtf_list= os.listdir(path)

art_list=[x.replace('.rtf','') if x.endswith('rtf') else x for x in rtf_list]

#reading rtf docs
documents=[]
error = 0
for x in rtf_list:
     single_file_path=f"{file_path}/{x}"
     with open(single_file_path, 'r', encoding="utf-8") as txt:
       try:
        content = txt.read()
        text = rtf_to_text(content)
        documents.append(f"{text}\n")
       except: 
         error += 1
print(documents, '\n')

#creating the dataframe

df_dict = defaultdict(list)

bill_split = [txt.split('Billboard',1)[1].split('\n') for txt in documents]
clean_split = [[ele.strip() for ele in l if ele!= "" and ele!=' '] for l in bill_split]
dates = [l[1] for l in clean_split]

#metadata
df_dict['title'] += [txt.split('Billboard')[0].strip() for txt in documents]
df_dict['author'] += [l[0].replace('By', '').strip() for l in clean_split]
df_dict['month'] += [l[1].split()[0] for l in clean_split]
df_dict['year'] += [l[1].split(f", ")[1] for l in clean_split]
df_dict['text'] += list(set([txt.split(date)[1] for txt in documents for date in dates if date in txt]))

dataframe= pd.DataFrame(df_dict).drop_duplicates()
dataframe.to_csv('/content/drive/MyDrive/Tesi_Polifonia/dataset_2.csv',index=False)